#-- Lattice Semiconductor Corporation Ltd.
#-- Map run script generated by Radiant

set ret 0
if {[catch {

if {![file exists {/home/seb/ecam/robot/project/robot/impl_1}]} {
  file mkdir {/home/seb/ecam/robot/project/robot/impl_1}
}
cd {/home/seb/ecam/robot/project/robot/impl_1}

sys_set_attribute -gui on -msg {/home/seb/ecam/robot/project/robot/promote.xml}
msg_load {/home/seb/ecam/robot/project/robot/promote.xml}
des_set_project_udb -in {robot_impl_1_syn.udb} -out {robot_impl_1_map.udb} -milestone map -pm ice40tp
des_set_reference_udb -clean
map_set_option {pdc_file "/home/seb/ecam/robot/project/robot/robot.pdc"}
# map option
map_set_option { report_symbol_cross_reference false report_signal_cross_reference false   ignore_constraint_errors false}
map_run

} out]} {
   puts $out
   set ret 1
}
exit -force ${ret}
